import type { Charity } from "./types";

// Illustrative, fictional causes for demo purposes — not real nonprofits.
// Cost-per-unit figures are calibrated to be realistic (large food banks
// commonly cite roughly $0.10–$0.25 per meal), not pulled from any real org.
export const charities: Charity[] = [
  {
    id: "harvest-table",
    name: "Harvest Table",
    tagline: "Cooks and delivers hot meals to families facing food insecurity.",
    emoji: "🍲",
    accent: "#E2703A",
    tint: "#FBEAE0",
    costPerUnitCad: 0.2,
    unitSingular: "meal",
    unitPlural: "meals",
    describeImpact: (n) => `${n} hot meal${n === 1 ? "" : "s"} delivered this week`,
  },
  {
    id: "clearwell-project",
    name: "Clearwell Project",
    tagline: "Builds and repairs wells so villages get clean drinking water.",
    emoji: "💧",
    accent: "#3C9D8F",
    tint: "#E3F3F0",
    costPerUnitCad: 0.2,
    unitSingular: "litre",
    unitPlural: "litres",
    describeImpact: (n) => `${n} litre${n === 1 ? "" : "s"} of clean water pumped`,
  },
  {
    id: "bright-page",
    name: "Bright Page Library",
    tagline: "Fills classroom shelves with books kids actually want to read.",
    emoji: "📚",
    accent: "#D9A441",
    tint: "#FBF1DD",
    costPerUnitCad: 1.5,
    unitSingular: "book",
    unitPlural: "books",
    describeImpact: (n) => `${n} storybook${n === 1 ? "" : "s"} placed in a classroom`,
  },
  {
    id: "small-paws",
    name: "Small Paws Shelter",
    tagline: "Feeds and cares for rescued dogs and cats until they're adopted.",
    emoji: "🐾",
    accent: "#C1666B",
    tint: "#FAE7E8",
    costPerUnitCad: 1.0,
    unitSingular: "day of care",
    unitPlural: "days of care",
    describeImpact: (n) => `${n} day${n === 1 ? "" : "s"} of shelter meals for a rescued animal`,
  },
  {
    id: "warm-nights",
    name: "Warm Nights Fund",
    tagline: "Hands out blankets and hot meals on cold city nights.",
    emoji: "🧣",
    accent: "#A65B3F",
    tint: "#F3E4DC",
    costPerUnitCad: 2.5,
    unitSingular: "bundle",
    unitPlural: "bundles",
    describeImpact: (n) => `${n} blanket + hot meal bundle${n === 1 ? "" : "s"} given out tonight`,
  },
  {
    id: "seedling-forest",
    name: "Seedling Forest Co.",
    tagline: "Plants native trees to help rebuild forests after wildfires.",
    emoji: "🌱",
    accent: "#6B8F55",
    tint: "#EAF1E3",
    costPerUnitCad: 0.5,
    unitSingular: "tree",
    unitPlural: "trees",
    describeImpact: (n) => `${n} native tree${n === 1 ? "" : "s"} planted`,
  },
  {
    id: "first-light-health",
    name: "First Light Health",
    tagline: "Runs mobile clinics that vaccinate kids in remote communities.",
    emoji: "🩺",
    accent: "#D98555",
    tint: "#FBEDE1",
    costPerUnitCad: 2.0,
    unitSingular: "vaccine",
    unitPlural: "vaccines",
    describeImpact: (n) => `${n} child${n === 1 ? "" : "ren"} vaccinated against measles`,
  },
];

export function getCharityById(id: string): Charity {
  return charities.find((c) => c.id === id) ?? charities[0];
}
